(() => {
  'use strict';
  const init = () => {
    const state={items:[{type:'deliverable',title:'Platform Architecture Audit',desc:'Review of AWS IoT Core + Kinesis pipeline. Written report with findings and recommendations.',qty:1,rate:85000},{type:'hourly',title:'Backend Engineering',desc:'Spring Boot service refactor, Lambda container optimization.',qty:42,rate:3500},{type:'fixed',title:'Monthly Retainer  April',desc:'On-call infrastructure support & advisory.',qty:1,rate:60000}]};
    const currencySymbols={INR:'₹',USD:'$',EUR:'€',GBP:'£',AUD:'A$',CAD:'C$',SGD:'S$',AED:'AED '};const typeLabels={deliverable:'Deliverable',hourly:'Per Hour',fixed:'Fixed Fee',discount:'Discount'};const $=id=>document.getElementById(id);
    const fmt=n=>{const cur=$('currency').value;return(currencySymbols[cur]||'')+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})};const fmtDate=d=>{if(!d)return'';return new Date(d).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})};
    function escapeHtml(s){return(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}function escapeAttr(s){return(s||'').replace(/"/g,'&quot;')}
    let logoDataUrl=null;const openLogo=()=>$('logoInput').click();$('logoDrop').addEventListener('click',openLogo);$('logoDrop').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openLogo()}});$('logoChange').addEventListener('click',e=>{e.stopPropagation();openLogo()});$('logoRemove').addEventListener('click',e=>{e.stopPropagation();logoDataUrl=null;$('logoContent').innerHTML='<div class="hint">Click to upload · PNG / JPG / SVG</div>';$('logoDrop').classList.remove('has-logo');$('logoActions').style.display='none';render()});$('logoInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=ev=>{logoDataUrl=ev.target.result;$('logoContent').innerHTML=`<img src="${logoDataUrl}" alt="logo">`;$('logoDrop').classList.add('has-logo');$('logoActions').style.display='flex';render()};r.readAsDataURL(f)});
    function renderItems(){const c=$('items');c.innerHTML='';state.items.forEach((it,i)=>{const el=document.createElement('div');el.className='item';const qtyLabel=it.type==='hourly'?'Hours':it.type==='deliverable'?'Qty':'Units';const rateLabel=it.type==='hourly'?'Rate / hr':'Rate';el.innerHTML=`<div class="item-head"><span class="item-index">${String(i+1).padStart(2,'0')}</span><div style="display:flex;align-items:center;gap:8px"><span class="item-type"><select data-k="type" data-i="${i}"><option value="deliverable" ${it.type==='deliverable'?'selected':''}>Deliverable</option><option value="hourly" ${it.type==='hourly'?'selected':''}>Per Hour</option><option value="fixed" ${it.type==='fixed'?'selected':''}>Fixed Fee</option></select></span><button class="item-remove" data-rm="${i}" title="Remove" aria-label="Remove line item">✕</button></div></div><div class="row"><label>Title</label><input type="text" data-k="title" data-i="${i}" value="${escapeAttr(it.title)}"></div><div class="row"><label>Description</label><textarea data-k="desc" data-i="${i}">${escapeHtml(it.desc||'')}</textarea></div><div class="row two"><div><label>${qtyLabel}</label><input type="number" step="0.01" min="0" data-k="qty" data-i="${i}" value="${it.qty}"></div><div><label>${rateLabel}</label><input type="number" step="0.01" min="0" data-k="rate" data-i="${i}" value="${it.rate}"></div></div>`;c.appendChild(el)});c.querySelectorAll('[data-k]').forEach(input=>input.addEventListener('input',e=>{const i=+e.target.dataset.i,k=e.target.dataset.k;let v=e.target.value;if(k==='qty'||k==='rate')v=parseFloat(v)||0;state.items[i][k]=v;if(k==='type')renderItems();render()}));c.querySelectorAll('[data-rm]').forEach(b=>b.addEventListener('click',e=>{const i=+e.target.dataset.rm;state.items.splice(i,1);if(!state.items.length)state.items.push({type:'deliverable',title:'',desc:'',qty:1,rate:0});renderItems();render()})}
    $('addItem').addEventListener('click',()=>{state.items.push({type:'deliverable',title:'New item',desc:'',qty:1,rate:0});renderItems();render();setTimeout(()=>{const inputs=$('items').querySelectorAll('input[data-k="title"]');inputs[inputs.length-1]?.focus()},0)});
    function render(){const logoWrap=$('pvLogo'),companyName=$('fromName').value||'Your Company';logoWrap.innerHTML=logoDataUrl?`<img src="${logoDataUrl}" alt="logo">`:`<div class="placeholder">${(companyName[0]||'L').toUpperCase()}</div>`;$('pvCompany').textContent=companyName;$('pvCompanyMeta').textContent=$('fromAddress').value;$('pvNumber').textContent=$('invNumber').value;$('pvToName').textContent=$('toName').value;$('pvToAddress').textContent=$('toAddress').value;$('pvIssue').textContent=fmtDate($('issueDate').value);$('pvDue').textContent=fmtDate($('dueDate').value);$('pvProject').textContent=$('project').value||'';$('pvNotes').textContent=$('notes').value;$('pvPayment').textContent=$('payment').value;$('pvFromFooter').textContent=`${companyName}\n${$('fromAddress').value}`;$('pvThanks').textContent=$('thanks').value;const tbody=$('pvItems');tbody.innerHTML='';let subtotal=0;state.items.forEach(it=>{const amount=(parseFloat(it.qty)||0)*(parseFloat(it.rate)||0);subtotal+=amount;const tr=document.createElement('tr');tr.innerHTML=`<td><div class="item-title">${escapeHtml(it.title||'Untitled')}</div>${it.desc?`<div class="item-desc">${escapeHtml(it.desc)}</div>`:''}<div class="item-mode">${typeLabels[it.type]}</div></td><td class="num">${it.type==='hourly'?`${it.qty} hr`:it.qty}</td><td class="num">${fmt(it.rate)}${it.type==='hourly'?' /hr':''}</td><td class="num">${fmt(amount)}</td>`;tbody.appendChild(tr)});const discRate=parseFloat($('discount').value)||0,taxRate=parseFloat($('taxRate').value)||0,discAmt=subtotal*discRate/100,afterDisc=subtotal-discAmt,taxAmt=afterDisc*taxRate/100,total=afterDisc+taxAmt;$('pvSubtotal').textContent=fmt(subtotal);if(discRate>0){$('rowDiscount').style.display='flex';$('pvDiscRate').textContent=discRate;$('pvDiscount').textContent='− '+fmt(discAmt)}else $('rowDiscount').style.display='none';$('pvTaxLabel').textContent=$('taxLabel').value||'Tax';$('pvTaxRate').textContent=taxRate;$('pvTax').textContent=fmt(taxAmt);$('rowTax').style.display=taxRate>0?'flex':'none';$('pvTotal').textContent=fmt(total)}
    ['fromName','fromAddress','toName','toAddress','invNumber','issueDate','dueDate','project','currency','taxRate','taxLabel','discount','payment','notes','thanks'].forEach(id=>$(id).addEventListener('input',render));
    const today=new Date();$('issueDate').value=today.toISOString().slice(0,10);const due=new Date(today);due.setDate(due.getDate()+15);$('dueDate').value=due.toISOString().slice(0,10);
    $('printBtn').addEventListener('click',()=>window.print());$('resetBtn').addEventListener('click',()=>{if(confirm('Reset all fields?'))location.reload()});
    document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();window.print()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openLogo();const h=$('shortcutHint');h.textContent='Upload your business logo';h.classList.add('is-visible');setTimeout(()=>h.classList.remove('is-visible'),1600)}});
    renderItems();render();
  };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init, { once: true });
  else init();
})();
